[second attempt] Fix the Java source code generation failure for OM class whose corresponding table lacks a PK.
Observed behavior before this patch:

Compilation error in BaseYourObject.setQueryKey(String) due to throws
delcaration mismatch between Torque's BaseObject.setPrimaryKey(String)
method and lack of generated setPrimaryKey(String) method.  Had the
override been generated, it would've had a throws declaration of
TorqueException, instead of Exception as declared by BaseObject.

  [javac] .../BaseYourObject.java:392:9:392:26: Semantic Error: The
  method "void setPrimaryKey(java.lang.String $1) throws
  java.lang.Exception;" can throw the checked exception
  "java.lang.Exception", so its invocation must be enclosed in a try
  statement that catches the exception, or else this method must be
  declared to throw the exception.

* src/generator/src/templates/om/Object.vm
* src/generator/src/templates/om/ObjectWithManager.vm
  Wrap the invocation of setPrimaryKey(String) in a try/catch block to
  re-throw Exception as TorqueException in the setQueryKey(String)
  method.

CollabNet-internal issue: PCN33929


git-svn-id: http://svn.apache.org/repos/asf/db/torque/trunk@229656 13f79535-47bb-0310-9956-ffa450edef68